### PR TITLE
test: Add routing tests

### PR DESCRIPTION
**Pull request by chapterjason**
Just noticed the missing support for Symfony below 4.1. 

https://github.com/symfony/symfony/pull/26085

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you. I appriciate this. But I think we should bump our composer.json to only support symfony versions that are currently maintained.  (or soon to be maintained)

Ie, 4.4, 5.3, 5.4 and 6.0.

**Comment by chapterjason** [comment]
@Nyholm Created another pr to focus on the supported version. #46

**Comment by chapterjason** [comment]
@Nyholm I was searching for the Issue and noticed that the we can deprecate also the `PublicCompilerPass`, it doesn't make sense since Symfony 4.1 cause of the `test.service_container`, just if we will stick now to 4.4.*<.

**Comment by chapterjason** [comment]
Wait for #47

**Comment by chapterjason** [comment]
@Nyholm Should also be ready now.

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
