### PR TITLE
feat: Symfony 7 support

### PR DESCRIPTION
**Pull request by kbond**

### CODE REVIEW

**Comment by smoench** [comment]
@kbond Anything I can support you here to get this PR merged? Except for fixing CI with this [PR](https://github.com/SymfonyTest/symfony-bundle-test/pull/84)

**Comment by kbond** [comment]
@smoench forgot about this one. I'll take a look in a few days but if you know how to fix the CI, go ahead!

**Comment by chapterjason** [comment]
As Symfony 7 support also brings support for php >=8.2 we also should test against php 8.2 and 8.3.

**Comment by chapterjason** [comment]
Please rebase your changes, add php 8.2 and 8.3, and adjust against the currently supported symfony versions: https://symfony.com/releases

**Review by chapterjason — CHANGES_REQUESTED** [review]
Sorry, currently a bit busy these days. 😄 

- [x] rebase
- [x] add php 8.2 and 8.3
- [x] adjust symfony versions: https://symfony.com/releases
- [x] adjust the changelog

**Comment by chapterjason** [comment]
@Nyholm Hey, please have a look at this.

I would like to drop those versions, as I think it is time to move forward.
As these are major changes what do you think about create a 3.0?

**Comment by Nyholm** [comment]
Yeah. I agree with dropping versions below 5.3 too. 

Releasing 3.0 makes it more clear we did that. And the upgrade path would be easy anyways since there is little to no code change.

**Review by Nyholm — APPROVED** [review]

**Comment by verschoof** [comment]
@chapterjason When do we get a new tag (release)?

**Comment by Nyholm** [comment]
I just merged the (what I think is) last code PR before tagging 3.0. 

Can you test dev-master in your app ang give a thumbs up if it is working as expected?

**Pull request merged**
